steps:
  # Print the contents of the current directory
  - name: 'ubuntu'
    args: ['ls', '-la']

  # Print the contents of the Dockerfile
  - name: 'ubuntu'
    args: ['cat', 'Dockerfile']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${REPO_NAME,,}:$COMMIT_SHA', '.']

options:
  logging: CLOUD_LOGGING_ONLY
